//------------------------------------------------------------------------------
// <auto-generated>
//     Työkalu muodosti tämän koodin.
//     Suorituksenaikainen versio:4.0.30319.42000
//
//     Tähän tiedostoon tehdyt muutokset saattavat aiheuttaa virheellistä toimintaa. Ne menetetään, jos
//     koodi muodostetaan uudelleen.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class Nights {
    
    private List<Night> nightField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Night")]
    public List<Night> NightList {
        get {
            return this.nightField;
        }
        set {
            this.nightField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class Night {
    
    private System.DateTime startTimeField;
    
    private System.DateTime endTimeField;
    
    private double timeSleptInMinutesField;
    
    /// <remarks/>
    public System.DateTime StartTime {
        get {
            return this.startTimeField;
        }
        set {
            this.startTimeField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime EndTime {
        get {
            return this.endTimeField;
        }
        set {
            this.endTimeField = value;
        }
    }
    
    /// <remarks/>
    public double TimeSleptInMinutes {
        get {
            return this.timeSleptInMinutesField;
        }
        set {
            this.timeSleptInMinutesField = value;
        }
    }
}
